from pymongo import MongoClient
from gridfs import GridFS
import pandas as pd
import tqdm
import requests
import urllib.request as request #urllib3版本要<=1.25否则会与requests版本冲突
from bs4 import BeautifulSoup
from progressbar import ProgressBar
import json
import  ast
from jsonpath import jsonpath
from tkinter import _flatten #将二维列表转成一维列表
import copy


error_UPID_list = ['A6H8Y1','P08579','Q06190','Q969Q6','Q99437','Q9Y5P8']

mongoClient = MongoClient('mongodb://172.10.10.9:27017/')
dtmr_dev = mongoClient.get_database('dtmr_dev')
dtmr_dev.authenticate('dtmr_dev', 'dtmr_dev')

dev = dtmr_dev.get_collection('uniprot_Target_Info_test')
for UPID in error_UPID_list:
    html_url = "https://rest.uniprot.org/uniprotkb/" + UPID
    response = request.urlopen(html_url)
    html = response.read()
    # print("html:", html)
    temp_dict = str(html).split("b'")[1].strip("'")

    eval(temp_dict)
    '''字符串转字典出现SyntaxError: EOL while scanning string literal   说明字符串中的引号和括号有未正确匹配成队'''
    # print('real_dict的数据类型为：', type(real_dict))
    '''此时需要转换思路，用beautifulsoup解析html源码'''
    # soup = BeautifulSoup(html, 'html.parser')#解析器为html.parser
    html_url = "https://www.uniprot.org/uniprotkb/P05067/entry"





record1 = {"UPID":"A6H8Y1", "TargetID":"A6H8Y1", "Protein_english_name":"Transcription factor TFIIIB component B'' homolog",
          "Alternate_Name":["Alternate_Name","Transcription factor-like nuclear regulator"],
          "Gene":"BDP1","Gene_synonyms":["KIAA1241","KIAA1689","TFNR"],
          "Organism":"human",
          "Function":"General activator of RNA polymerase III transcription. Requires for transcription from all three types of polymerase III promoters. Requires for transcription of genes with internal promoter elements and with promoter elements upstream of the initiation site.",
          "Sequence":"MFRRARLSVKPNVRPGVGARGSTASNPQRGRESPRPPDPATDSASKPAEPTDVPTVDFGGAEPQEKAPRSSTEKTGGDNDVEESSRSSSTVSQRRKRISSTSSLVKSSVSVPSESHPLSTINQEAPQPTATSTKEKQPCSDRYRIYKAQKLREMLKEELRKEKKQWKNKYAINESQRPPDRSKMTMRDFIYYLPDNNPMTSSLEQEKKTEKPSTPVQTREQEGKSTPNAEDNEMEEETDDGPLLVPRVKVAEDGSIILDEESLTVEVLRTKGPCVVEENDPIFERGSTTTYSSFRKNYYSKPWSNKETDMFFLAISMVGTDFSMIGQLFPHRARIEIKNKFKREEKTNGWRIDKAFQEKRPFDFDFFAHLLQKVLAEEEKRKQKSVKNHSLKEKKSTKPRKNVKVKKVACEGVNNDPDESMSSRISDTERSQKDAQTVEEESLTLSREDAEQVALEVDLNQKKRRRKKQDGANELGVNNLLENATVQAGPSKGEKHKNKCQAIRPELKEGECSKEQMLSCTQNIDGIVGFASTEKVEKRTDPILSLSNQQDATSVATESSESSTSDLPSFEVGIRALCEVNNAEGSCIEERNVDLKNNSLEIDQTENVKPMLRGRFQRPKPNLSRAGKKSVLSQGKTESESKNSHSKTSVEKNHVEKDKMNTLDILRMETTERENPEAETVSVLGEKNCLQEGSQLKALRPVQVRGRLQKPKPNAGKAAERKEILISQEEIGANVEKNENESCADRDTPQHMEDQSRKDFEEEDVILQPEKNDSFQNVQPDEPKVLNECLSVQENNKANKLNQVPILRTRFQKPKPNIGRGTGRREISSKEEVLEKILVSGEMAAALRETVRLDTSPKEMVPAEINTKEMQSDLKETGRRAISPREKILDVIDDTIEMETGLKAMGREICLREKTPEVIDATEEIDKDLEEAGRREISPQKNGPEEVKPLGEVETDLKATGNESSPREKTPEVTDATEEIDKNLEETGRRKISPRENGPEEVKPVDEMETDLNATGRESSPREKTPEVIDATEEIDLEETEREVSPQENGLEEVKPLGEMETDLKATGRDSFPRGKTPEVIDAIEEIEIDLEETEREISPQENGLEEVKPLGEMQTDLKATGREISPREKTPEVIDATEEIDKDLEETGRREISPEENGPEEVKPVDEMETDLKTTGREGSSREKTREVIDAAEVIETDLEETEREISPQENGPEEVKPVGKMETDLKEIREEISQREKVLAEFSAIREKEIDLKETGKRDIPIMEKVSGKMAVVEEMEADLKETGKENFRERGSEEICVTEEKVAELKQTGKTDISPRENELEETSTSRQTDTHLMQSGSNDFSAVPSLDIQNISSEVLSMMHTPVEEKRNSEKEVSSHFSHFKISSQTHESDKTEVQGIQSPDVPEQFSDINLSKSLPQEQKPLEIKPAPFVRSRFKRPKPNLARAALKRETTESEKYIYEKKSETKKMETIVMQENNEQTDTLPSQHDEASLMISREKDTLGHRNEEAVILPCTQTERNLSPSNSCEPKEESQSAPVQKNDSVVSVGTNNVNTFQQEMKESVIQTARQVRGRLQRPRPNIRKTGQRQIVDKGEAKGIIKEGRTILPKDETEKKVLTVSNSQIETEIEVPSSAVPEHRMYENQSQVVLVENLHVNKTNETIRHENKPYVPSSAQMTRRKFQKAKPNLGRAHSKKEEPVLEKVTTDQSKEGKPEDHLLQKGASNTQLLLKEKAELLTSLEVSARKDCVGSKESALAKIDAELEEVGPSRRVGEETVGDNSPSSVVEEQYLNKLTSCPQPLNETSYSKIALDGKTTISSTSEYERNRGERRSHKKFKPNVTRGRGSKRVRGKTSKKEPRASKAMLVTLRASQEEDDDADDFESDYEEESYHLAPEEVNKAPVFVPVGLRSPEPVSAQIEETMEELEITVNVPDVGCIAVVEHELPNTDVTTEEMKQEENLSVPFEMTTSEHIQDEPGTNDGSTEAAITLLTMGDLVLQSEISSEQGDVGVCIIPHVHSKDKSHIPSSLDNVNHKIVHECQELSSPVITTSPASFEENKIVLEEQSSREEISLMEKVKENATPTRNTISKVTSNLRIRSRLAKPKPNLEKTLGTNRLDDYQEVSSLCVTKGAEMETQRETEKNASKATELENKNLGPVTTAENKDQSKLACVHGIKGTSISSEVNLTERNENQEESSQEVHMLSVAPVASSETGPCTLGLDRGLGENSVEEPQIKDSKGDSVLTLPVPEYTPTSIPEVQQENIINPQDLTVNLVANVPQDGEDEQAFILTLVEIPANAVEEFTDATAQFMPNPLLPAPILVKSVNTEERGDMSICLPATSVGQDAMGLSISGRDNSKKPPDNLDLVSRKRFQCRLDKNDHIPPAKKRSLTLRDDCQEYTTEVHSKELTNVFEETGESHKGQDIFLTSGSTLTTPEPQRQQVEAAFQSRGSRSPDACMDKNVPQLPQDEMIVSDKEERTDAAPKSQQMDSRTSSSKASLSRPGRRPLGFLSLICSKNSLESDEPMQVHSKKRLKPLIPGLRKKLKRSNPFNESQEKNRESSDLLPSPSVITTQSENISSSATQVSCDQPLLKEGYKSAQKRAPQGEATTVSEYFFNDIFIEVDETE",
          "Binding_site":[],
          "Structure_AlphaFold":{"Source":"AlphaFoldDB",
                                 "IDENTIFIER_entryId":"AF-A6H8Y1-F1",
                                 "gene":"BDP1"
                                 },
          "Structure_PDB":[],
          "Relate_disease":"null",
          "Binding_pocket":"null",
          "Postivecompound":"null",
          "Remark":"null",
          "Topology":"null",
          }

record2 = {"UPID":"P08579", "TargetID":"P08579", "Protein_english_name":"U2 small nuclear ribonucleoprotein B''",
          "Alternate_Name":["Alternate_Name","Transcription factor-like nuclear regulator"],
          "Gene":"BDP1","Gene_synonyms":["KIAA1241","KIAA1689","TFNR"],
          "Organism":"human",
          "Function":"General activator of RNA polymerase III transcription. Requires for transcription from all three types of polymerase III promoters. Requires for transcription of genes with internal promoter elements and with promoter elements upstream of the initiation site.",
          "Sequence":"MFRRARLSVKPNVRPGVGARGSTASNPQRGRESPRPPDPATDSASKPAEPTDVPTVDFGGAEPQEKAPRSSTEKTGGDNDVEESSRSSSTVSQRRKRISSTSSLVKSSVSVPSESHPLSTINQEAPQPTATSTKEKQPCSDRYRIYKAQKLREMLKEELRKEKKQWKNKYAINESQRPPDRSKMTMRDFIYYLPDNNPMTSSLEQEKKTEKPSTPVQTREQEGKSTPNAEDNEMEEETDDGPLLVPRVKVAEDGSIILDEESLTVEVLRTKGPCVVEENDPIFERGSTTTYSSFRKNYYSKPWSNKETDMFFLAISMVGTDFSMIGQLFPHRARIEIKNKFKREEKTNGWRIDKAFQEKRPFDFDFFAHLLQKVLAEEEKRKQKSVKNHSLKEKKSTKPRKNVKVKKVACEGVNNDPDESMSSRISDTERSQKDAQTVEEESLTLSREDAEQVALEVDLNQKKRRRKKQDGANELGVNNLLENATVQAGPSKGEKHKNKCQAIRPELKEGECSKEQMLSCTQNIDGIVGFASTEKVEKRTDPILSLSNQQDATSVATESSESSTSDLPSFEVGIRALCEVNNAEGSCIEERNVDLKNNSLEIDQTENVKPMLRGRFQRPKPNLSRAGKKSVLSQGKTESESKNSHSKTSVEKNHVEKDKMNTLDILRMETTERENPEAETVSVLGEKNCLQEGSQLKALRPVQVRGRLQKPKPNAGKAAERKEILISQEEIGANVEKNENESCADRDTPQHMEDQSRKDFEEEDVILQPEKNDSFQNVQPDEPKVLNECLSVQENNKANKLNQVPILRTRFQKPKPNIGRGTGRREISSKEEVLEKILVSGEMAAALRETVRLDTSPKEMVPAEINTKEMQSDLKETGRRAISPREKILDVIDDTIEMETGLKAMGREICLREKTPEVIDATEEIDKDLEEAGRREISPQKNGPEEVKPLGEVETDLKATGNESSPREKTPEVTDATEEIDKNLEETGRRKISPRENGPEEVKPVDEMETDLNATGRESSPREKTPEVIDATEEIDLEETEREVSPQENGLEEVKPLGEMETDLKATGRDSFPRGKTPEVIDAIEEIEIDLEETEREISPQENGLEEVKPLGEMQTDLKATGREISPREKTPEVIDATEEIDKDLEETGRREISPEENGPEEVKPVDEMETDLKTTGREGSSREKTREVIDAAEVIETDLEETEREISPQENGPEEVKPVGKMETDLKEIREEISQREKVLAEFSAIREKEIDLKETGKRDIPIMEKVSGKMAVVEEMEADLKETGKENFRERGSEEICVTEEKVAELKQTGKTDISPRENELEETSTSRQTDTHLMQSGSNDFSAVPSLDIQNISSEVLSMMHTPVEEKRNSEKEVSSHFSHFKISSQTHESDKTEVQGIQSPDVPEQFSDINLSKSLPQEQKPLEIKPAPFVRSRFKRPKPNLARAALKRETTESEKYIYEKKSETKKMETIVMQENNEQTDTLPSQHDEASLMISREKDTLGHRNEEAVILPCTQTERNLSPSNSCEPKEESQSAPVQKNDSVVSVGTNNVNTFQQEMKESVIQTARQVRGRLQRPRPNIRKTGQRQIVDKGEAKGIIKEGRTILPKDETEKKVLTVSNSQIETEIEVPSSAVPEHRMYENQSQVVLVENLHVNKTNETIRHENKPYVPSSAQMTRRKFQKAKPNLGRAHSKKEEPVLEKVTTDQSKEGKPEDHLLQKGASNTQLLLKEKAELLTSLEVSARKDCVGSKESALAKIDAELEEVGPSRRVGEETVGDNSPSSVVEEQYLNKLTSCPQPLNETSYSKIALDGKTTISSTSEYERNRGERRSHKKFKPNVTRGRGSKRVRGKTSKKEPRASKAMLVTLRASQEEDDDADDFESDYEEESYHLAPEEVNKAPVFVPVGLRSPEPVSAQIEETMEELEITVNVPDVGCIAVVEHELPNTDVTTEEMKQEENLSVPFEMTTSEHIQDEPGTNDGSTEAAITLLTMGDLVLQSEISSEQGDVGVCIIPHVHSKDKSHIPSSLDNVNHKIVHECQELSSPVITTSPASFEENKIVLEEQSSREEISLMEKVKENATPTRNTISKVTSNLRIRSRLAKPKPNLEKTLGTNRLDDYQEVSSLCVTKGAEMETQRETEKNASKATELENKNLGPVTTAENKDQSKLACVHGIKGTSISSEVNLTERNENQEESSQEVHMLSVAPVASSETGPCTLGLDRGLGENSVEEPQIKDSKGDSVLTLPVPEYTPTSIPEVQQENIINPQDLTVNLVANVPQDGEDEQAFILTLVEIPANAVEEFTDATAQFMPNPLLPAPILVKSVNTEERGDMSICLPATSVGQDAMGLSISGRDNSKKPPDNLDLVSRKRFQCRLDKNDHIPPAKKRSLTLRDDCQEYTTEVHSKELTNVFEETGESHKGQDIFLTSGSTLTTPEPQRQQVEAAFQSRGSRSPDACMDKNVPQLPQDEMIVSDKEERTDAAPKSQQMDSRTSSSKASLSRPGRRPLGFLSLICSKNSLESDEPMQVHSKKRLKPLIPGLRKKLKRSNPFNESQEKNRESSDLLPSPSVITTQSENISSSATQVSCDQPLLKEGYKSAQKRAPQGEATTVSEYFFNDIFIEVDETE",
          "Binding_site":[],
          "Structure_AlphaFold":{"Source":"AlphaFoldDB",
                                 "IDENTIFIER_entryId":"AF-A6H8Y1-F1",
                                 "gene":"BDP1"
                                 },
          "Structure_PDB":[],
          "Relate_disease":"null",
          "Binding_pocket":"null",
          "Postivecompound":"null",
          "Remark":"null",
          "Topology":"null",
          }